
[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 66
port = 1212
allowdupeip = true

[game]
hostname = "MyServer"
mapname = "SavedEntities.xml"
maxplayers = 32
type = 1
welcomemsg = "Welcome to the server!"

[console]
width = 120
height = 60
