[package]
name = "robust-native-server"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
mimalloc = { workspace = true }
robust-native-shared = { path = "../robust-native-shared" }
